config/routes.rb
Rails.application.routes.draw do
  root to: "messages#index"

  #
  # DEVISE
  #
  devise_for :users, controllers: { 
    sessions: "users/sessions",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    unlocks: "users/unlocks"
  }

  #
  # GROUPS
  #
  get 'groups/new', to: 'groups#new', as: 'new_group'
  post 'groups/create', to: 'groups#create', as: 'create_new_group'
  get 'groups/invite_member', to: 'groups#invite_member', as: 'invite_member_to_group'

  #
  # MESSAGES
  #
  post 'messages/create', to: 'messages#create', as: 'new_message'
  get 'messages/index', to: 'messages#index', as: 'messages'

  #
  # TOPICS
  #
  post 'topics/create', to: 'topics#create', as: 'new_topic'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_member
  has_many :messages
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  def self.users_in_groups(user_id)
    groups = where(user_id: user_id).pluck(:group_id)
    users = where(group_id: groups).pluck(:user_id)
    User.where(id: users).order(:name)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :message, presence: true, length: {maximum: 2000}
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :group_member
  has_many :messages

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  expose(:action) { path[:action] }

  expose(:current_group_id) { 1 }

  expose(:group_names) { User.pluck(:name) }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  expose(:new_group) { Group.new }

  expose(:common_members) { GroupMember.users_in_groups(current_user.id) }

  def new
    # create a new group
  end

  def invite_member
    # add a member to a group
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  expose(:testing) { "This is a test" }

  expose(:message) { Message.new }

  expose(:messages) { Message.order("created_at ASC") }

  expose(:topics) { Topic.order("created_at DESC") }

  expose(:topic) { Topic.new }
  
  def index
    # load all threads and messages for preferred group id, unless custom group id is defined
  end

  def create
    respond_to do |format|
      @message = Message.create(message_params)
      format.html {redirect_to root_url}
      format.js
    end
  end
 
  private
 
  def message_params
    params.require(:message).permit(:message, :user_id, :group_id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   build_resource(sign_up_params)
  #   p "TESTING TESTING"
  #   if resource.save
  #     yield resource if block_given?
  #     set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
  #     expire_data_after_sign_in!
  #     respond_with resource, location: after_inactive_sign_up_path_for(resource)
  #   else
  #     clean_up_passwords resource
  #     respond_with resource
  #   end
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def after_sign_up_path_for(resource)
  #   '/an/example/path' # Or :prefix_to_your_route
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/new.html.erb
<%= simple_form_for(
  new_group, 
  url: create_new_group_path,
  html: { class: "form-horizontal" }, 
    wrapper: :horizontal_form,
    wrapper_mappings: {
      check_boxes: :horizontal_radio_and_checkboxes,
      radio_buttons: :horizontal_radio_and_checkboxes,
      file: :horizontal_file_input,
      boolean: :horizontal_boolean
    } 
  ) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.association :group_member, 
    label: "Invite Friends and Family", 
    collection: common_members, 
    as: :check_boxes %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-text">Welcome, <%= current_user.name %>!</p>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left nav-pills">
        <li role="presentation" class="<%= 'active' if controller_name == 'groups' %> dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Groups <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Group 1</a></li>
            <li><a href="#">Group 2</a></li>
            <li><a href="#">Group 3</a></li>
            <li><a href="#">More Groups...</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="<%= new_group_path %>">Create A Group</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Join A Group</a></li>
            <% unless (controller_name == "groups" && action_name == "new") %>
              <li role="separator" class="divider"></li>
              <li><a href="#">Configure This Group</a></li>
            <% end %>
          </ul>
        </li>
        <li role="presentation" class="<%= 'active' if controller_name == 'messages' %>">
          <a href="<%= root_path %>">Messages</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialite</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
    <% if current_user %>
      <%= render 'layouts/navbar' %>
    <% end %>
    
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{name == 'notice' ? 'success' : 'danger'}" %>
    <% end %>
  
    <%= yield %>
  
  </body>
</html>

app/views/messages/_form.html.erb
<div class="well" id="messages-form-well">
  <%= simple_form_for(
    message, 
    url: new_message_path,
    html: { class: "form-inline" }, 
    remote: true
    ) do |f| %>
    <%= f.input :message, label: false %>
    <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
    <%= f.input :group_id, as: :hidden, input_html: { value: current_group_id } %> 
    <%= f.submit 'Message', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/messages/_message.html.erb
<li class="message">
  <p><%= message.user ? message.user.name : "Wooops" %>: <%= message.message %></p>
</li>

app/views/messages/_messages.html.erb
<div id="messages">
  <ul class="media-list">
    <% messages.each do |message| %>
      <li class="message">
        <p><%= message.user ? message.user.name : "Wooops" %>: <%= message.message %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/messages/create.js.erb
publisher = client.publish('/messages', {
  message: '<%= j render @message %>'
});
 
publisher.callback(function() {
  $('#message_body').val('');
  $('#new_message').find("input[type='submit']").val('Message').prop('disabled', false)
});
 
publisher.errback(function() {
  alert('There was an error while posting your comment.');
});

app/views/messages/index.html.erb
<div class="fluid-container">
  <div class="row">
    <div class="col-md-4">
      <div id="topics-container">
        <%= render 'new_topic' %>
        <%= render 'topics' %>
      </div>
    </div>
    <div class="col-md-8">
      <div id="messages-container">
        <%= render 'messages' %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>